### PR TITLE
moving to es6

### PR DESCRIPTION
**Pull request by stoeffel**
How about moving to es6?
* Before the tests are run or a new build is created, all `.es6`-files are transpiled to es5 into the `dist` folder.
* tests are run using the transpiled files

If you think it's overkill close this PR. Personally, I think es6 is much more fun to write :smile: .

### CODE REVIEW

**Comment by adrai** [comment]
My strategy is to wait for the es6 features to be stable...
That's why I'm not going to merge it (right now) but I will not close this PR ;-)
Thanks for your interest :-)

**Comment by stoeffel** [comment]
> My strategy is to wait for the es6 features to be stable...

The nice thing about [babel](https://babeljs.io/) is, you don't have to wait.

> That's why I'm not going to merge it (right now) but I will not close this PR ;-)

sure :-)

> Thanks for your interest :-)

NP

**Comment by TooTallNate** [comment]
I'd be :+1: for this (but _not_ committing the compiled `dist` dir to the repo, that should be a "prepublish" step instead).

More info: http://rauchg.com/2015/ecmascript-6/

**Comment by adrai** [comment]
@stoeffel would you like to do the prepublish and update to current master?

**Comment by adrai** [comment]
@stoeffel or if you prefer you can do a new pull request...

**Comment by stoeffel** [comment]
@adrai sure I will update this PR.

**Comment by stoeffel** [comment]
I will let you know when it's ready :smile:

**Comment by stoeffel** [comment]
Okay, I rebased and applied all changes to `enum.es6` and `enumItem.es6`.

`gulp test` compiles the es6-files runs the tests and removes all compiled files after the test are completed.
`gulp build` compiles all es6-files into `dist`.

**Comment by adrai** [comment]
ok, when the next release is ready (waiting for a new feature or a bug) it will be powered by "ES6-force" ("stoeffel-force") ;-)

**Comment by stoeffel** [comment]
May the force be with you.

**Comment by jasonkarns** [comment]
I see this has already been merged, but I am :-1: on this. Using babel will eliminate any chance of IE8 support, and will make IE9 & 10 support much trickier (babel sort-of supports 9 and 10 but means one must be selective with the ES6 features used).

Related: I opened #18 to document what level of IE support is actually desired/intended. And I created [a branch](https://github.com/jasonkarns/enum/tree/internet-explorer) that fixes IE support (down to at least IE8) by simply aborting the freezing process.

**Pull request merged**
